
package ru.mndsc.bigarch.wsclient.bl.organizationservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.5-b03-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "OrganizationEntityService", targetNamespace = "http://organization.zdms_component.mndsc.ru/", wsdlLocation = "file:/home/itiu/work/dmsc.copy/big-archive-client-web/bacw-import/src/main/resources/OrganizationEntityService.wsdl")
public class OrganizationEntityService
    extends Service
{

    private final static URL ORGANIZATIONENTITYSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(ru.mndsc.bigarch.wsclient.bl.organizationservice.OrganizationEntityService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = ru.mndsc.bigarch.wsclient.bl.organizationservice.OrganizationEntityService.class.getResource(".");
            url = new URL(baseUrl, "file:/home/itiu/work/dmsc.copy/big-archive-client-web/bacw-import/src/main/resources/OrganizationEntityService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/home/itiu/work/dmsc.copy/big-archive-client-web/bacw-import/src/main/resources/OrganizationEntityService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ORGANIZATIONENTITYSERVICE_WSDL_LOCATION = url;
    }

    public OrganizationEntityService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrganizationEntityService() {
        super(ORGANIZATIONENTITYSERVICE_WSDL_LOCATION, new QName("http://organization.zdms_component.mndsc.ru/", "OrganizationEntityService"));
    }

    /**
     * 
     * @return
     *     returns OrganizationEntityEndpoint
     */
    @WebEndpoint(name = "OrganizationEntityServiceEndpointPort")
    public OrganizationEntityEndpoint getOrganizationEntityServiceEndpointPort() {
        return super.getPort(new QName("http://organization.zdms_component.mndsc.ru/", "OrganizationEntityServiceEndpointPort"), OrganizationEntityEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrganizationEntityEndpoint
     */
    @WebEndpoint(name = "OrganizationEntityServiceEndpointPort")
    public OrganizationEntityEndpoint getOrganizationEntityServiceEndpointPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://organization.zdms_component.mndsc.ru/", "OrganizationEntityServiceEndpointPort"), OrganizationEntityEndpoint.class, features);
    }

}
