
package ru.mndsc.bigarch.wsclient.bl.organizationservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.5-b03-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "OrganizationServiceException", targetNamespace = "http://organization.zdms_component.mndsc.ru/")
public class OrganizationServiceException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private OrganizationServiceException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public OrganizationServiceException_Exception(String message, OrganizationServiceException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public OrganizationServiceException_Exception(String message, OrganizationServiceException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ru.mndsc.bigarch.wsclient.bl.organizationservice.OrganizationServiceException
     */
    public OrganizationServiceException getFaultInfo() {
        return faultInfo;
    }

}
